### ISSUE TITLE
ui edit

### ISSUE THREAD

**Issue by rowanibrahem** [AshrafSholok/Chat_app#5]
صغر حجم ايقونة الواتس شوية و اكتب كلمة whats app تحت الايقونة و خليهم في النص متسبش مسافات كبيرة كدا بين الايقونة و اخر جملة

**Comment by AshrafSholok** [comment]
![Screenshot_1728349221](https://github.com/user-attachments/assets/4624fa8e-70a5-446a-93f0-94fced7534d0)

**Comment by rowanibrahem** [comment]
good work
