### ISSUE TITLE
edit hierarchical folder

### ISSUE THREAD

**Issue by rowanibrahem** [AshrafSholok/Chat_app#6]
هنا جوه ال constants فايل عادي اسمه asset_images 
اللي جنب constants دا يتشال ملوش لازمة و عدل اسم الفايل نفسه 
![image](https://github.com/user-attachments/assets/68e5354a-8ce5-4bb5-b6ba-fda31749f95b)

**Comment by AshrafSholok** [comment]
![Screenshot 2024-10-08 040313](https://github.com/user-attachments/assets/c57f7c2c-5d6c-441d-b2fb-3fec11557dd1)

**Comment by rowanibrahem** [comment]
good job
