### ISSUE TITLE
refactor splash code 

### ISSUE THREAD

**Issue by rowanibrahem** [AshrafSholok/Chat_app#7]
الكود كويس و صغير بس ممكن يتعمله refactor برضو انك تحط في الview ال scaffold و تاخد الbody تحطه في كلاس تاني جوه فولدر الwidgets 
يعني الview يكون فيها 
scaffold (
body: SplashBody(),
);
و تعمل فولدر الwidgets جوه الview و تعمل جواه فايل splash_body و تعمل class بقي عادي فيه كود الbody 
ممكن تجربها و لو معرفتش او مظبطتش ابعتلي  
![image](https://github.com/user-attachments/assets/e0173fea-f621-42e8-9dfb-f053f213a6de)

**Comment by AshrafSholok** [comment]
![Screenshot 2024-10-08 040554](https://github.com/user-attachments/assets/9699a36a-c52d-4980-8396-cf2ab7313e35)

**Comment by rowanibrahem** [comment]
حلو اوي متنساش ترفع التعديلات علي البرانش
